name: PR Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - release/**
      - hotfix/**

jobs:
  test:
    name: Run Tests on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run Unit Tests with more info
        run: mvn test -B -Dspring.profiles.active=test -X

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/