name: Spring Boot PR Validation

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - release/**
      - hotfix/**

jobs:
  validate:
    name: Validate and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Verify code formatting
        run: mvn spotless:check
        continue-on-error: true
      
      - name: Run static code analysis
        run: mvn pmd:check
        continue-on-error: true
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
          
      - name: Run Unit Tests
        run: mvn test -B -Dspring.profiles.active=test
      
      - name: Generate test reports
        if: always()
        run: mvn surefire-report:report-only
        
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/site/
